#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi


export FZF_DEFAULT_OPTS="--reverse"
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
export VIRTUAL_ENV_DISABLE_PROMPT=1
export KUBE_PS1_SEPARATOR=""
export KUBE_PS1_SYMBOL_DEFAULT=""
. "$HOME/.cargo/env"
export PATH="/Users/lucadrf/.local/bin:/Users/lucadrf/fltk/bin:$PATH"
