#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Set up fzf key bindings and fuzzy completion
source <(fzf --zsh)

eval "$(pyenv init - zsh)"


# Aliases
alias ll="ls -lah"
alias llt="ls -laht"
alias vim="nvim"
alias kc="kubectl"
alias kx="kubectx"
alias kn="kubens"
alias kon="kubeon"
alias koff="kubeoff"
